title: Charting Canons: Identities and Institutions Behind Bestselling and Award-Winning American Fiction From 1913 to 2023
description: Data on the gender, race, education, and publishers of bestselling and award-winning authors of American fiction from 1913 to 2023.

publisher_text: K. M. Arrington
publisher_url: 

license_text: 
license_url: 

frequency: Once (Sept. 2024)

certificate_embed: 
